name: 'gh-action-calculate-nx-affected-head-base'
description: 'Calculate shas for NX affected command.'
author: 'goran.mrzljak@gmail.com'
inputs:
  main-branch-name:
    required: true
    description: 'The name of the main branch of your repo, e.g `master`'
  version-bump-commit-message-summary-matcher:
    required: true
    description: 'RegExp used to match version bump commit message summary (first line of commit message), so that it can be skipped in `nx affected` calculation. Example: `^chore\\(release\\): `'
outputs:
  base:
    description: 'The value intended to be used in `nx affected --base`'
  head:
    description: 'The value intended to be used in `nx affected --head`'
runs:
  using: 'node12'
  main: 'dist/index.js'
